### ISSUE TITLE
Hamburger menu icon not universally understood as trigger for mobile menu

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-testing#101]
@onezerojeremy commented on [Wed Jun 15 2016](https://github.com/18F/fec-style/issues/396)

User did not understand the hamburger icon was the trigger for the menu. 

🔧 Hamburger menu might not be effective for various users different levels of computer literacy/less text and mobile savvy users.

[Navigation feature set in research repo](https://github.com/18F/FEC/blob/master/feature_sets/ia_primary_nav_menu.md)
tagging: @jenniferthibault @noahmanger @jeanninehunter @emileighoutlaw @edmullen as likely interested parties.

**Comment by JonellaCulmer** [comment]
Similar to issue #88
