### ISSUE TITLE
Test updated election summary designs with data users

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-testing#108]
Referencing issue #106 from fec-testing as that pertained to testing election summary pages from the recent usability testing in Scottsdale. After synthesis there are a few design tweaks that we should test further.

@JonellaCulmer Please provide @patphongs with the updated sketch designs for the election summary pages so that we can code this up before 5.3 testing.

**Comment by JonellaCulmer** [comment]
Issue moved to [fecgov/fec-cms #1869](https://github.com/fecgov/fec-cms/issues/1869) via [**ZenHub**](https://www.zenhub.com/)
