### ISSUE TITLE
Test auth committee to auth candidate linkage

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-testing#109]
**What we're testing:**
Are users confused when switching from the committee profile page to viewing the candidate profile page?

Do users have an easy time getting from the committee page to the authorized candidate page?

**What's implemented:**
The current implementation is that the user will be linked to the authorized candidate from the committee profile page based on cycle selected. They will only be viewing 2 year slices at a time unless otherwise changed in the candidate profile page to view the entire election year.

**Hypotheses:**
Advanced data users are familiar with seeing data in 2 year slices, so they will not be confused with the linkage and the data they see on the candidate page. 

Newer users may be confused as to what time period of data they are looking at.

**Comment by JonellaCulmer** [comment]
So far we've conducted 3 usability tests this week and have plans to test with two other individuals next week.

**Comment by JonellaCulmer** [comment]
Testing using the following script: https://docs.google.com/document/d/1NT-2FR0EcAVlC1WzeJp5rW_s8WRlMTH6SqFsAmFE-V8/edit#

**Primary findings:** 
- Users successfully located the relevant information. Half of the testers use the new button on the left nav and the other went to the About this committee tab and found relevant information on the callout card.
- Nearly all participants clicked on the authorizing candidate when they needed to get to the candidate's profile page.
- Users could all identify the two-year periods and determine money raised during a particular period. 

**Other findings:** 
- Users had trouble finding "all years" from the committee page. Think the assumption was that this kind of information would be on the committee page, not the candidate page.
- Users were able to locate candidate committees a variety of ways, primarily by using the global search and the candidate advanced data table. 
- It was unclear to users whether the candidate was running in an upcoming election. The candidate in question was listed as an incumbent, but not listed on the election profile page. By the latter point, users assumed that he was not running but found nothing definitive.

Issue resulting from testing: 
- API searching for indiv. contrib. data outside of two-year period with modified URL: https://github.com/fecgov/fec-cms/issues/1960
