### ISSUE TITLE
COGEL user testing

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-testing#119]
**What we're after:** We will be conducting user testing at the COGEL conference again this year. 

We hope to test the following areas of the website: 

- ADR data table
- AF data table (possibly)
- Boolean search
- Visualizations
- Processed vs. Raw
- ZZ codes on individual contributor and all receipts data tables
- candidate profile page, filings tab
- Homepage banners

To prepare for this testing we need to do the following:
- [x] Mock-up data visualizations (@JonellaCulmer)
- [x] Finish basic version of AF (@patphongs)
- [x] Implement boolean search updates (@johnnyporkchops) 
- [x] Create InVision prototypes (@JonellaCulmer)
- [x] Write test script(s), including identifying testing locations (feature, dev, stage, etc)(@JonellaCulmer)
- [x] Print signage (@JonellaCulmer)
- [x] Print out consent forms (@JonellaCulmer)
- [x] Print new usability testing flyers and remember stickers (@JonellaCulmer)
- [x] Compile results from testing

**Comment by patphongs** [comment]
@JonellaCulmer I'm hoping to have a fully functioning AF prototype for you to test with for the conference. The datatable page prototype is done, just need to make the canonical page now.

**Comment by JonellaCulmer** [comment]
Summary presentation for COGEL research here: https://docs.google.com/presentation/d/1acCvMwkQRuGbgLwxyXuTZrFrRGwdV58wz-633zvLs1U/edit#slide=id.g2549073cbc_1_205
