### ISSUE TITLE
Research questions for breakdown pages

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-testing#13]
As we’re building out the raising and spending breakdown pages ([epic](https://github.com/18F/fec-epics/issues/29) and [epic](https://github.com/18F/fec-epics/issues/30)), I’m finding some questions / things to keep tabs on. I’m going to log them here so we don’t lose track:
- Where should the links to underlying data take you? Itemized transactions? Reports? Candidate / committee data pages?
- How do users handle the side nav and the conceptual link between the “Overview” charts on the home page and the “Breakdown” pages?
- Should we be including top-level totals on the breakdown pages (like cycle-to-date totals)?
- Do we need an introductory explanation on the breakdown pages?

These are just a few things that popped up when reviewing the implementation with @jenniferthibault . I'm sure there will be more.

**Comment by jenniferthibault** [comment]
OOh yay using the new repo! Thanks for tracking these here, Noah.
