### ISSUE TITLE
Fix line breaks in Votes data for MURs

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#27]
While gathering feedback on the canonical page designs for the legal resources (see https://github.com/18F/fec-testing/issues/24), a user noted that the data in the `Votes` section for MURs appears as a giant paragraph, when it really should be broken into multiple lines. Here is what he said:

> On the MUR page, where the Votes are. I think that’s a very helpful feature, having the votes listed. I wonder if it could be listed in 1-2-3. To have each recommendation be its own line, rather than a block of paragraph text, that would be nice.

To give this issue more context, here is how one of the paragraphs in question currently appears:
<img width="662" alt="screen shot 2017-01-14 at 1 24 34 pm" src="https://cloud.githubusercontent.com/assets/1450173/21957499/1b01ea60-da5d-11e6-95ea-8733380fefd7.png">

And here is the desired appearance:

<img width="668" alt="screen shot 2017-01-14 at 1 25 18 pm" src="https://cloud.githubusercontent.com/assets/1450173/21957505/2ce018d8-da5d-11e6-8132-b68363ed6496.png">

Based on the database demo provided by Jennie and the FEC team, it seems as though this is a problem in the source system. Therefore, I am not sure if/how we will address this.

**Comment by noahmanger** [comment]
I thought we were redesigning these pages to present the votes as a table rather than paragraphs?

**Comment by nickykrause** [comment]
@noahmanger the votes themselves appear as a table, yes:

<img width="829" alt="screen shot 2017-01-17 at 8 35 47 am" src="https://cloud.githubusercontent.com/assets/1450173/22024555/f941ffb6-dc8f-11e6-9c1a-171393725ef4.png">

But there are paragraphs within the table regarding each of the "recommendations" that was made for that particular voting session.
