### ISSUE TITLE
Does the "Filter this Data" button that appears on candidate and committee pages clearly communicate its purpose? 

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#36]
In testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Testing-Script-3-9-17.md), one advanced user (a university researcher working constantly with this data) found the `Filter this data` button to be confusing. She was looking at the Individual Contributions for a Committee, on a page like this:

![image](https://cloud.githubusercontent.com/assets/1450173/23768789/c3c67734-04d2-11e7-855c-2aa5555024f8.png)

She said that she couldn't find a way to see the "raw data," and, when asked what she thought about the "Filter this data" button, she said she expected it to allow her to further narrow and categorize the data, beyond the state-by-state categorization/filtering that she was already seeing. She said she wanted to see _all_ the data, which she referred to as "raw."

This was only one user, so we don't have a clear signal about this, but I'm logging it as a question for now, for us to watch/consider.

**Comment by nickykrause** [comment]
FYI @emileighoutlaw and @jenniferthibault

**Comment by jenniferthibault** [comment]
This seems super related to  https://github.com/18F/openFEC-web-app/issues/1869

**Comment by nickykrause** [comment]
Yes, it is, @jenniferthibault ! Thank you for linking. More evidence! :tada:
