### ISSUE TITLE
User request: Sign up to receive alerts when new filings are posted for a specific candidate/committee

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#37]
In testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Testing-Script-3-9-17.md), one advanced user (an investigative reporter specializing in campaign finance) requested the ability to sign up for alerts regarding specific candidates and committees. She wanted to be alerted by email when new reports became available, rather than having to remember to return to the candidate/committee page on a regular basis.

**Comment by nickykrause** [comment]
We received this request again in testing on Friday 5/19

**Comment by patphongs** [comment]
I've also heard this request several times in other testing, but it was not documented here. Moving this up to a finding.

**Comment by JonellaCulmer** [comment]
We've now added this functionality in a separate feature.
