### ISSUE TITLE
Does the visual styling of search filters make it hard to tell what is selected?

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#40]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-3-31-17-AOs.md), one user commented that the visual styling of the radio buttons for the AO citation filters was confusing because it was "hard to tell which one was selected." 

The user pointed out that the one with the filled-in radio button looks selected, and he compared that to an answer bubble on a standardized exam. However, he said that the unselected option _also_ appeared selected because it seemed to be "highlighted":

![image](https://cloud.githubusercontent.com/assets/1450173/24816763/9fc7fbe4-1b9f-11e7-8ca9-9b22601c72ba.png)

When I asked if he felt this would be resolved in a case where there were more than two options, he said "maybe," but then looked to the list of checkboxes for AO documents and said he still felt the problem existed there:

![image](https://cloud.githubusercontent.com/assets/1450173/24816807/cc93fbf0-1b9f-11e7-81b2-31652ab4fbd3.png)

**Comment by jenniferthibault** [comment]
Thinking particularly about the radio buttons, when faced with only two options, you don't get a sense of the model for what is selected & what is deselected.

One first small change we could make is to differentiate just the radio button selected state. I've added a small gap between the fill and the outline here to try that out, and visually I think it helps show which dot is filled in:

![screen shot 2017-05-09 at 3 39 12 pm](https://cloud.githubusercontent.com/assets/11636908/25869286/cf999246-34cd-11e7-93e2-feb23cf7d329.png)

Trying to focus on style changes that I have a higher likelihood of being able to make myself :)

**Comment by PaulClark2** [comment]
Keep open 6/14/19
