### ISSUE TITLE
Users suggest that Time Period filters in AO filter panel could make input requirements clearer and offer more options

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#46]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-3-31-17-AOs.md), the users were presented with a task that asked them to search for all AOs about a specific topic that were issued in 2014 or later.

The users followed the expected path and entered the topic into the keyword field, after which they proceeded to add date parameters. However, when they accessed the `Time Period` accordion to input the dates, all three of them commented that they weren't sure which dates were required. 

For reference, the date filters look like this:
![image](https://cloud.githubusercontent.com/assets/1450173/24818482/5fe4b560-1ba6-11e7-9ee3-e12499adaa73.png)

The users did not know if they needed to enter both a beginning and an ending date, which made them feel somewhat uncertain about their search results

In the end, two users input Jan 1, 2014 as the starting date and nothing as the ending date, while the third user put in an end-date of the current day. 

One user suggested that he would want clear options like `after this date,` `before this date,` and `between this date.` His rationale was that, a lot of times, he may be unclear about what the beginning date should be because he does not know when the AOs started. He also explained that this convention exists in WestLaw, and he sent a screenshot, with the words: 

> I personally could do without the “last x months/years…” options but think 4 would be really helpful – all dates before, all dates after, specific date, and date range.

![image](https://cloud.githubusercontent.com/assets/1450173/24818813/93119e98-1ba7-11e7-9ffc-2065f9eb6b70.png)

**Comment by patphongs** [comment]
The AO time period filter is there now live on the website so we can test it live.
