### ISSUE TITLE
User request: Add more graphical/visual representations of data to committee pages

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#49]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-3-31-17-Committee.md), one user commented that he would really like to see more charts and graphs of the data on the committee pages. He said he also appreciated seeing just the straightforward list of numbers (e.g., the `Financial Summary` tab), but that he also liked the pie charts and visual representations of the data that were offered on the legacy site.

An example of a place where he suggested having a chart was on the `Disbursements` tab for a committee (see screenshot below)

He added that he consults for candidates who are running campaigns and that he likes to be able to sit down with them and talk about how they are doing compared to their competitors, and that those visual summaries are very useful for facilitating those conversations.

![image](https://cloud.githubusercontent.com/assets/1450173/24819802/c085470e-1bab-11e7-8624-6ae70460c526.png)

**Comment by PaulClark2** [comment]
Keep open 6/14/19
