### ISSUE TITLE
Add a null state to the calendar to clarify why some months lack info

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#56]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-05-02.md), several users accessed the calendar in search of upcoming elections. In all three cases, the users applied the `All elections` filter (and a relevant `state` filter) and then paged through the months, looking for elections in their area.

Because the calendar does not have a "null" state, the users experienced some confusion when looking at months in 2018. Users were not sure whether the calendar lacked data simply because there was no election in their area for the month shown (e.g., Nov 2018), or if there was just no data loaded for that point in the future. Consequently, the users weren't sure what conclusion to draw about upcoming elections.

<img width="1262" alt="screen shot 2017-05-16 at 9 14 09 am" src="https://cloud.githubusercontent.com/assets/1450173/26110698/b5c371f2-3a18-11e7-9a01-79049c4bed7b.png">

**Comment by JonellaCulmer** [comment]
We have designed a state to address this null event. Here is the implementation issue: https://github.com/fecgov/fec-cms/issues/2315
