### ISSUE TITLE
Users struggle to find information on nearby elections via the campaign finance data menu

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#57]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-05-02.md), three of the four users struggled to find "upcoming elections near [them]" because they chose to use the Calendar instead of taking the expected path (Main menu > Campaign finance data > Look up elections by location). When users were asked whether or not they thought any of the menu options might help them, they said no. When directly asked about `Campaign finance data` (CFD) as a possible home for the information they needed, all three of the users said they would "never" have thought to look there.

In light of these observations, it seems that we should consider moving the election info out of the CFD menu. However, it is worth noting that the phrasing of the question may have pushed users toward the calendar, because it had a temporal element to it: `Can you find out if there are any elections coming up near you?`   If we had simply asked `Can you find elections near you?`, the outcome may have been different.

The one user who did succeed with this task did not find the answer via CFD. He used the homepage module.

**Comment by nickykrause** [comment]
Results from this round of testing: 

> In previous tests, almost all users struggled with this question because they went to the calendar instead of to the CFD > Elections area. We slightly reworded the question for this test because we wanted to see if removing the word "upcoming" would change the approach that people took to answering it. The answer to that seems to be no. Again, in this test, two of the three users initially thought to use the calendar. One person said "I would guess that would be in upcoming events on the homepage." He clicked on "All events" and added a filter for the state of Arizona on the calendar, thinking it would show him all events in AZ. The state filter stayed open and blocked the "All elections" filter.  One of the three users did go to the CFD menu, but only after looking at and slowly reading all of the contents of the other two menu fly-outs.

Across all of the tests combined, **we now have 5/7 users who went to the Calendar to find upcoming elections, as opposed to the CFD menu.** Many of the users who were asked about this choice acknowledged that they never would have thought to go to CFD for information about elections. 

Users have variously suggested (1) a revival of the "map" info on the old site, (2) moving `Elections` to be its own main menu item, (3) Putting `elections` as a menu option near the calendar, and (4) adding something more visually prominent to the homepage about upcoming elections. (Of course, it should be noted: Users often suggest these kinds of things when trying to accomplish a specific task--i.e., they say "add a menu item for it" or "move it to the top")

**Comment by nickykrause** [comment]
One last comment here: Perhaps if the question were asked in the past tense, the results would be different. If users were asked: `Can you find information about the elections in Illinois in 2016?`, then maybe the mental model would be different, and it would indeed trigger them to look at the CFD menu.

Basically, I wonder if looking for information from the past seems like a data task, whereas looking for information about something nearby or something upcoming feels different.

**Comment by nickykrause** [comment]
Update: Tested this with two more users this week, without having a temporal component to the question. 

The first user succeeded easily in finding elections information via the `CFD` menu, without any prompting. T

he second user went to H4CC -> Dates and deadlines -> Compliance Map. It turned out that when she looks for information about elections by state, it is because she wants to know about the different primary dates, and she knew that the old site housed that info in the "compliance map." Consequently, she assumed the elections would live in a section related to compliance. She ultimately had to be directed to `CFD`, where she acknowledged she wouldn't think to look for election-related info.

Overall, this new data brings us to **6/9 users not expecting elections info to appear in `CFD`.**

Interestingly, there is not a clear signal as to where people _do_ expect elections data to appear. Several have thought of the calendar, but, again, that may have been due to the temporal phrasing of the original question. Since rephrasing the question, some users have still thought of the calendar, but others have thought of CFD or even H4CC, and the choice seems largely influenced by what happens to interest them about elections. Perhaps this is a weak signal that `Elections` info deserves its own home?

**Comment by noahmanger** [comment]
Interesting. This seems like valuable data to feed into this issue: https://github.com/18F/openFEC-web-app/issues/2070, and seems to suggest that there might be some real value in combining dates, compliance info and data, since users will expect to come from multiple directions.

**Comment by PaulClark2** [comment]
Keep open 6/14/19
