### ISSUE TITLE
User request: Remove two-year limit on advanced data filtering

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#63]
This issue has come up multiple times in the past, but it came up again in a recent test, so I thought I'd log it as something we know (and have known for a while) from user research/testing.

Basically, users want to be able to look at more than one two-year period at a time when filtering the advanced data tables. Most recently, while testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-05-12.md), one user brought this up in the context of browsing Individual Contributions data. The user looked up a specific person and wanted to be able to see that individual's contribution history by applying a date range from 1979 - 2017. This was not possible, of course, and the user commented that it was frustrating to be limited to two-year periods when viewing the data.

**Comment by JonellaCulmer** [comment]
In the process of removing the two-year period limitation to receipts and individual contributions. So closing.
