### ISSUE TITLE
Browse receipts button does not transfer date parameters from candidate profile to advanced data table

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#64]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-05-02.md), the `Browse receipts` button on the candidate profile page seemed to be malfunctioning. (However, it is possible that it is working as designed -- I am not sure?) 

The user was looking at Hillary Clinton’s presidential candidate page, on the Financial Summary tab (https://beta.fec.gov/data/candidate/P00003392/?election_full=True&cycle=2016&tab=summary). 

The default election cycle there is 2016. He was looking for more detailed information about Hillary’s receipts from that election--specifically, receipts from the state of Illinois--so he clicked the `Browse receipts` button. 

He was surprised to see that the advanced data table had no results, and we realized that the table was filtered on 2017-2018 (instead of 2015-2016, which was the date range for the table he came from).

It seems like the `Browse receipts` button (and the `Browse disbursements` button) from the candidate’s Financial Summary should carry over the election cycle selection into the data table.

Noah mentioned that [this may have been fixed by this PR](https://github.com/18F/openFEC-web-app/pull/2013), but then, when we talked about it during the demo last week, it wasn't 100% clear that it was the same issue. If I'm mistaken and it's already been fixed, we can close this.

**Comment by JonellaCulmer** [comment]
This has been corrected, so closing.
