### ISSUE TITLE
Should we adjust the visual display of totals on the Financial Summary for Candidates and Committees?

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#65]
In the past three rounds of testing, we have had 9 total participants. Of these, two of them have failed to notice that the dark gray bar on the `Financial Summary` pages contain the totals for a given section (e.g., Raising or Spending). 

In both cases, when the totals were pointed out to them, the users commented that they hadn't even seen those lines and that they assumed they were headers. They both said the bar seemed too dark, or that maybe it was confusing that it was at the top of the table instead of the bottom. 

Here is an screenshot of the Receipts section of the Financial summary

![image](https://cloud.githubusercontent.com/assets/1450173/26314099/80010fd4-3ed2-11e7-8781-111eca05c4fa.png)

**Comment by PaulClark2** [comment]
Keep open 6/14/19
