### ISSUE TITLE
Navigating to main website sections

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-testing#83]
Get started button was not intuitive for users to go to the main landing page of a section. One person said "Get started refers more to tutorial language".  

Some questions that still need to be answered:
1) Is the button needed?
2) Are users expecting a button to get to the landing page?
3) Now that the main sections have been removed to clean up the site homepage, are users still able to navigate to the main sections via the site menu.

**Comment by JonellaCulmer** [comment]
Getting started button issue also raised in #67.

> You work for a candidate's authorized committee and have received a donation from a foreign national. You want to know if you can accept that donation or not. Can you find the answer to that question using this website?

"In this case, many users did go to H4CC and successfully click on the Get started button to access the H4CC landing page. However, there were a small proportion of users who went to H4CC and seemed to miss the button, and ended up at legal resources instead (which is possibly fine?)"

"In summary: Although there have been many successes with the H4CC menu, especially with the latter question, there is a small group of people who don't seem to understand that H4CC contains more than what is listed in the menu, and who may be missing useful information."

>

**Comment by JonellaCulmer** [comment]
Following up on the DC FEC Conference, we continued to observe users not using the Get started button to access key relevant information on the H4CC landing page. We will move forward with mocking up different solutions to addressing this issue.

**Comment by JonellaCulmer** [comment]
Based on previous research, the top-level navigation/menu was used to conduct A/B testing at the Scottdale conference in February. 

The A/B testing involved two version of the menu: 
- complete removal of the menu, with the exception of the About menu
- modified menu featuring ">>" next to the menu header to improve it's appearance as a link, not just a title, and changed the "Get started" button text to "Learn more" in all website menu sections (CFD, H4CC and Legal)

We learned the following things about these menu designs: 
- **Users had more success finding the guides without a menu, and more success finding dates and deadlines with a menu.** The level of importance for some of our content is not consistent. Dates and deadlines is in the H4CC menu, but towards the bottom of the H4CC landing page. 
- **Users did not notice the changes made on the modified menu.** We did not observe any testers attempt to select either the menu header or the button formerly known as Get started. Adding the carrots to the header and modifying the button text did not seem to increase traffic to the landing pages.
- **Confused by the menu titles in modified menu test, uncertain of which section would help them most.** At the conference we observed users visit multiple sections before determining which would help them the most. There back and forth between H4CC and CFD, and H4CC and Legal resources.

Next steps: 
We are mocking up redesigns of our menus, here: https://github.com/fecgov/fec-cms/issues/1799

**Comment by JonellaCulmer** [comment]
Updated menu mock-ups:
![updated-menu-cfd](https://user-images.githubusercontent.com/31663028/38502813-71c2528e-3bde-11e8-805e-ba58eb86ed0e.png)
![updated-menu-h4cc](https://user-images.githubusercontent.com/31663028/38502825-7e315916-3bde-11e8-9ed4-65025651c2ce.png)
![updated-menu-legal](https://user-images.githubusercontent.com/31663028/38502830-8335486e-3bde-11e8-8ea2-c4edf33f9de7.png)
![updated-menu-about](https://user-images.githubusercontent.com/31663028/38502843-885a56e0-3bde-11e8-8ae4-c1b51b353c8b.png)
