### ISSUE TITLE
Pre classic shutdown analytics research

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-testing#93]
*What we're after:* 
Use analytics to understand and help users transition from classic to new website. 

**Research questions:** 
- [ ] Look at the classic site analytics to reverse engineer what users will be looking for the most on the classic site. We need to figure out what users are accessing the most.
- [ ] Where are users coming from to get to popular sections on classic site? 

Let's slate this one for Sprint 4.3.

**Comment by JonellaCulmer** [comment]
This sheet includes the links on classic.fec.gov used most as of September 25. This can serve as a jumping off point based on the latest stats.

https://docs.google.com/spreadsheets/d/1HEtra2lBlS-CViqtbTA1gdnmg06jxrkdrP9GT4JCpiw/edit#gid=0

**Comment by AmyKort** [comment]
This is great! Thank you!

**Comment by patphongs** [comment]
@JonellaCulmer Let's try to merge these 2 spreadsheets together to get a clearer picture of what redirects need to happen: https://docs.google.com/spreadsheets/d/1y6HiGeOAfeMWyPIzHqRoyYqYjVRBiYlxNNEm5gJ87Dc/edit#gid=0

**Comment by JonellaCulmer** [comment]
Closing this ticket as it's extremely out of date. If we need to revisit this we can reopen or create a new ticket.
