### ISSUE TITLE
Continue to Test the Analyst Contact Form

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-testing#97]
Following the FEC DC Conference, it is still unclear as to whether users are finding the analyst contact form. While some users did not have trouble locating the form once already on the contact page, users did not have the same level of success when starting from the homepage. 

Completion criteria:
- [ ] Using research (recent and past) develop mock-ups of new Contact page layout
- [ ] Test new mock-ups prototype

Previous contact issue: https://github.com/18F/fec-testing/issues/89

**Comment by patphongs** [comment]
Closing this issue as this has been tested in the past. We don't need to do additional testing at this point. Will revisit if that changes.
